### PR TITLE
Add a title to the TimePickerDialog (solves #16)

### PR DESCRIPTION
**Pull request by geecko86**
Just use .setTitle() on a TimePickerDialog instance and you're good to go. Of course, this is all optional and there is no title by default.

Let me know if I messed up something, feel free to rename stuff :).

### CODE REVIEW

**Comment by geecko86** [comment]
Here's how it looks

Screenshot

**Comment by wdullaer** [comment]
Nice :-)
I'll try to free up some time this weekend to treat all the pull requests and do a new release.

I'm also sorry I didn't take a look at this sooner. This is literally a side project of a side project.

**Comment by wdullaer** [comment]
I'd like this to have the same design as the weekday name on the datepicker.
This will make your title smaller and all caps. Does that work for you?

I also think that the reason google doesn't include a title in their picker designs is because the context from where you launch the picker should make it obvious what the picker is for.

**Comment by geecko86** [comment]
It's definitely not something that's needed in all cases. In my case it's simply because I need the user to input two separate hours in order to define when to start/stop using the night theme, similar to what you can see in the first screenshot above.

I'll have a look.

**Comment by wdullaer** [comment]
I'll push a new branch with my proposal to github in a minute. Let me know what you think.

I'm also looking at getting dark theme support in the date picker.

**Comment by geecko86** [comment]
Mh, not too sure about the upper case..

**Comment by wdullaer** [comment]
It keeps things consistent between both pickers, although it de-emphasizes your title.

**Comment by wdullaer** [comment]
If the uppercase really doesn't work out for you, let me know and I'll see if I can refactor it into a theme you can override.

**Pull request merged**
