### PR TITLE
master

### PR DESCRIPTION
**Pull request by kenumir**
Add more customization options - change color of ok/cancel buttons

### CODE REVIEW

**Comment by wdullaer** [comment]
I'm reluctant to merge this one in.
It's not part of the material design pickers specification. In general I think the audience for this is very small.
Every feature I put in, I need to explicitly support. Not only in testing when I do changes, but also in answering support questions for people who have absolutely no clue on how to use it.

**Comment by skywall** [comment]
+1

**Comment by Rainer-Lang** [comment]
Button color is in accent color (guidelines).

**Comment by wdullaer** [comment]
I'm going to close this pull request.
The goal of the library is to offer a picker in line with the material design specs, this feature violates that.

If you like to use this you can always fork the library, nothing wrong with that. In fact it's the beauty of open source that I don't need to add configuration options for everything.
I like this library to remain at least a bit focussed. I don't want it to turn  into all things for all men.

**Pull request closed without merging**
