### PR TITLE
Create README_ES.md

### PR DESCRIPTION
**Pull request by LuigiBaute**
Let me know if you got any suggestions, I'll gladly change it as many times as necessary. :)

### CODE REVIEW

**Comment by LuigiBaute** [comment]
@wdullaer check it out :+1:

**Comment by LuigiBaute** [comment]
@wdullaer Hi, do you have an idea of what went wrong with the file? so I can change it... I've been reviewing it and can't tell what happened...

**Comment by wdullaer** [comment]
Don't worry about the CI. 50% of the time it fails because travis doesn't properly save the android sdk license agreement. There's no consistency to it.
I'm trying to figure out a workaround.

**Comment by wdullaer** [comment]
README looks good (as far as my tourist Spanish goes)
I'll link to this one from the mail README

**Comment by LuigiBaute** [comment]
Can I translate the license?  @wdullaer  btw. I'm so glad the pr worked out nice for you! :+1: CHEERS!

**Comment by wdullaer** [comment]
No, you shouldn't translate the license.
The wording in these is very specific and vetted by lawyers. The apache license is a very commonly used license, I think it's safe to assume that people can figure out how to comply with it.

**Pull request merged**
