### PR TITLE
Implementation for custom day abbreviations

### PR DESCRIPTION
**Pull request by omarzl**
Hi!

I implemented a solution so anyone can customize the day abbreviations, this could be helpful for some locales that gives us wrong abbreviations, in my case the "es_MX" locale is not available in every device so the locale give us a wrong abbreviation for Wednesday="X" instead of "M".

Please check the code and if there's all correct I hope you can add it to your library, it will help me a lot!!

Thank you!

I send you two screenshots of my tests.

customabbreviations
localeabbreviations

### CODE REVIEW

**Comment by wdullaer** [comment]
The idea is that the picker uses the locale of the user/device.
So if the device doesn't have a Mexican locale, it probably means the user is not Mexican and should see the picker in a different language, with different abbreviations.

Overriding the built in logic with a static list throws out all localisation.

Can you give a bit more detail on your usecase, because right now, I don't see the problem that this is solving.

**Comment by omarzl** [comment]
That sounds logic.
I made a little more of debug and I tell you whats my problem.
I used your library for an app in english and mexican spanish, and in the simulator and my physical device it shows correctly an "M" for wednesday.
But in some devices it shows an "X" for wednesday, and I though that it was because maybe the device doesn't have the locale "es_MX" as I pointed up in my first comment.
I tested in a "Moto G" and it shows correctly, then I get a "Samsung Galaxy Note 2" and in that device it shows wrong, I checked and the Build.VERSION.SDK_INT is 22 (Lollipop) so it means it doesn´t fall in the code:

if (locale.getLanguage().equals("es") && day.get(Calendar.DAY_OF_WEEK) == Calendar.WEDNESDAY)
                dayLabel = "X";

So my conclusion was that the native format "EEEEE" was giving me the "X" in this part of the code:

return new SimpleDateFormat("EEEEE", locale).format(day.getTime());

What I did is to log the locales and print the initial of the day using the format "EEEEE" and I send you the screenshots.

samsung galaxy note 2
moto g


It results that indeed it has the locale "es_MX" but for any variations of spanish it will always use an "X" in the "Samsung Galaxy Note 2" as you can see in the log.
Meanwhile the "Moto G" has the correct abbreviations.

I ask some friends to test it and they found out that this also occurs in a "LG K10", but the problem is only in some devices, most of them show correctly and none of them were rooted.

So I think that the solution could be to override the abbreviations to force that the show correctly for wednesday in locale "es_MX".

What do you think?
I dont get why some devices give me the "X" but it ocurrs /:

**Comment by wdullaer** [comment]
I reread the code and it's explicitly set to English because a Spanish user of the library opened an issue to have it changed that way.
(I'm not Spanish, so I have to rely on user input).
It just checks for the language, not the full locale, so I can set this to `es_ES` and then it should be fine in `es_MX`
This only applies to API version < 18, as google baked in the single letter weekday into android itself at API version 18.

I'm closing this PR and I suggest you open an issue so I don't forget to fix this

**Comment by omarzl** [comment]
I thought it was because of the API version < 18, but the error happens in a device with API version 22 (Lollipop), the error is not there, the native format "EEEEE" of the locale is what gives me wrong the abbreviation.

**Comment by wdullaer** [comment]
I'm pretty sure google spent some time getting the localisation for Spanish right.
If the default android localisation value is 'X' for a Wednesday for `es_MX`, then I'm going to keep it that way.

**Pull request closed without merging**
