### PR TITLE
Feature hour only

### PR DESCRIPTION
**Pull request by jdegroot**
Recreate pull request #210

### CODE REVIEW

**Comment by andriodteam** [comment]
how can i use the hourly selected in time?

**Comment by jdegroot** [comment]
@andriodteam call `setHourOnlyPicker(true) ` on your TimePickerDialog, then it won't auto advance to minute selection. (note: this is not merged/published yet, so you'll have to pull from my fork)

**Comment by andriodteam** [comment]
how can i pull it please can u tell me how to do it

**Comment by jdegroot** [comment]
@andriodteam 

- `git clone git@github.com:jdegroot/MaterialDateTimePicker.git`
- `git checkout feature_hour_only`
- Build the library with Gradle and move the aar your project

**Comment by andriodteam** [comment]
Permission denied (publickey). its giving me this issue

**Comment by jdegroot** [comment]
@andriodteam try https (https://github.com/jdegroot/MaterialDateTimePicker.git)

**Comment by andriodteam** [comment]
hello sir, it giving this error fatal: Not a git repository (or any of the parent directories): .git

**Comment by jdegroot** [comment]
@andriodteam What did you do exactly? You should just replace the url after clone with the https one:

`git clone https://github.com/jdegroot/MaterialDateTimePicker.git`

Then navigate to the folder where it was cloned and checkout the `feature_hour_only` branch. You might want to consider doing some git tutorials, Github has a [guides page](https://guides.github.com/)

**Pull request closed without merging**
