### PR TITLE
Fix problem with background color

### PR DESCRIPTION
**Pull request by nzakharchenko**
Some views were reusing background specified in theme for Dialog.
For more details see https://github.com/wdullaer/MaterialDateTimePicker/issues/430

### CODE REVIEW

**Comment by wdullaer** [comment]
I'll try to review this over the weekend, but on first inspection this looks good.

**Comment by wdullaer** [comment]
This looks good.
Would you be able to give the TimePickerDialog a similar treatment?

**Comment by nzakharchenko** [comment]
@wdullaer actually I've done changes for TimePickerDialog as well, and it should work well.

**Comment by wdullaer** [comment]
I'll try to make a new release somewhere this week with these changes

**Comment by nzakharchenko** [comment]
@wdullaer nice!!

**Comment by wdullaer** [comment]
My apologies for the delay, but I have finally gotten around to releasing this.

**Pull request merged**
