### PR TITLE
Optionally disable the rendering of DatePickerDialog's title and header

### PR DESCRIPTION
**Pull request by kombadzomba**
DatePickerDialog.setTitleVisibility() and DatePickerDialog.setHeaderVisibility() added.

### CODE REVIEW

**Comment by wdullaer** [comment]
I need to think about this.
It deviates from the google reference design and I'm not sure how many people would use this.

**Comment by wdullaer** [comment]
I've thought about this and I don't think I'll merge this.
Hiding the header and title makes it look like a calendar widget, which means people will start to use it as such.
This will in turn lead to a whole lot of issues because it wasn't designed to be used that way.

For these kind of changes it's probably best just to fork the library. Nothing wrong with that.

Please don't take it the wrong way. I really appreciate your effort and contribution, and in general deciding what to support is a very grey zone.

**Comment by kombadzomba** [comment]
Ok, no problem. Thanks for reply. Can you specify what issues may occur
since we plan to use it without header.

Header is fine but we like it more without it - it's minimalistic, not
overwhelming the user by repeating information.

**Comment by wdullaer** [comment]
I don't think you will have any issues in your use case.
As long as you use it as a datepicker it should all just be fine. The changes you've done are fairly minimal, so you should have no issues keeping them in sync with this library.

I'm reluctant to merge it in, because I don't want to have to support the feature. I'm thinking someone will start using it as part of a calendar app and come up with all sorts of feature requests and issues because I'm not testing for that use case.

Everyone is free, and even encouraged, to fork the code and use it for whatever they like, but my time to work on this is limited so I like to keep the use cases I support fairly focussed.

**Comment by kombadzomba** [comment]
Ok, no problem at all. Thanks for your time and for sharing your code with
community!

**Comment by wdullaer** [comment]
I did think of a drawback with hiding the header: you will no longer have access to the year picker (which you get to by tapping the year in the header)

**Pull request closed without merging**
