### PR TITLE
Color Accent FTW

### PR DESCRIPTION
**Pull request by Jawnnypoo**
This pull request allows the dialogs to take the colorAccent from the current context, either AppCompat or native 21+ colorAccent. It also allows dialogs to have their accent color set programatically. I also took the liberty to update the Support Lib versions and Android SDK, as well as the gradle version just for the sake of completeness. I also added a new app icon because it looked cool. Let me know what you think and if you have any questions!

### CODE REVIEW

**Comment by wdullaer** [comment]
Awesome pull request!
This is exactly what I had in mind, I just didn't have the time to do it yet. (Including the cleanup of unused statements leftover from the original google code)
I'll probably merge this in this weekend along with some other minor changes I have done in the mean time.

A few nitpicks:
* It probably makes more sense to default to `colorPrimary` rather than `colorAccent` (I misnamed the attributes in this library, hindsight is 20/20)
* The new icon looks great, but maybe a clock or calendar icon is more appropriate than a person icon?

Now that the icon looks good, maybe I can put the sample app on google play.

**Comment by Jawnnypoo** [comment]
Hey, I agree. I changed the calendar icon. I just went and generated it here:
http://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
As to the note about accent, the if you look at the Google apps that use the same calendar and time pickers, they all use the themes accent color to color the dialogs (see the settings app on Android 5.0+ when you go to change your time, or the Clock app on 5.0+). Therefore I think it does make sense to keep it pulling from the themes colorAccent. As for the name of the method, yeah maybe it would make more sense (since it is the primary color of the dialog) but I could see it working either way. 

Hope to see this merged in soon with another release, I am looking forward to using it in a few of my apps!

**Comment by wdullaer** [comment]
I've already merged this in a local copy.
I'm fixing some other bugs right now.
If all goes well, a new release should be out today.

I'm also thinking about externalising all the state that every component in the picker needs to know in a separate class. So rather than passing the accentColor or themeDark through the hierarchy, just pass that state object and have everything reference it. But that will probably be for a future release.

**Comment by Jawnnypoo** [comment]
Yeah that would make things much easier. It did feel weird having to add `setAccentColor` to so many places in the code.

 It would be nice to have it all centralized (which I guess is really what the purpose of a context theme would be, but I understand your desire to avoid including appcompat in the library to support using the colorAccent from the theme). Regardless, I think there will always be times where the user would want to set the color programatically without using the theme, so its a good thing to support. 

I looked at [Material Dialogs](https://github.com/afollestad/material-dialogs) as an inspiration for how some of these things should work. Its a great library to reference for a lot of things like this. Anyhow, thanks for all that you are doing and keep it up!

**Comment by wdullaer** [comment]
I've used Material Dialogs as a source of inspiration before.

I should see how they handle retaining the callbacks on an orientation change. I haven't figured out a good way to do this in the library itself. The only way I know how to do it now is via the onResume() of the parent Activity.

**Pull request merged**
