### PR TITLE
- Added on month changed functionality

### PR DESCRIPTION
**Pull request by gilcunningham**

### CODE REVIEW

**Comment by wdullaer** [comment]
Can you explain why you want this functionality?

The contract of the picker is that it notifies you when the user has selected a full date.
There are some internal callbacks which fire when UI elements change, but I hope to make these protected in the future as I don't intend to support that level of granularity. This is not a generic calendar widget.

**Comment by gilcunningham** [comment]
Firstly, this is a great library, looks great, easy to use.  I chose it primarily for the selectable and unselectable dates functionality.  My use case for the "on month changed" feature is that the server I work with provides a months worth of available (selectable) dates.  I could make a 12 calls and load a years worth, buts that wasteful.  If I had some callback to when the next month was selected, I could load the next + 1 month available days to buffer.

**Comment by wdullaer** [comment]
This functionality has been coded with the assumption that these dates are stable once you call show.
I would have to reread the code (and have a look at when a recyclerview renders / refreshes what) to see if it would actually lead to weird stuff, but I'm afraid that trying to replace these arrays at the time this callback fires can lead to strange race conditions.

I think a better approach would be to implement your own `DateRangeLimiter`(https://github.com/wdullaer/MaterialDateTimePicker/blob/master/library/src/main/java/com/wdullaer/materialdatetimepicker/date/DateRangeLimiter.java). The `isOutOfRange` method will be called when the picker is trying to render a particular date.
You could lazily load your disabled dates in your implementation of this interface and be sure that everything works as expected.
Using a custom `DateRangeLimiter` will disable the built-in one, but the code is available.

**Comment by gilcunningham** [comment]
FYI, got it all working with minimal effort by using swapAdapter() instead of setAdapter() in DayPickerView#refreshAdapter() and removing the setSelectedDay().  Working nicely now.

**Comment by wdullaer** [comment]
I'm happy you got it to work :-)
I do prefer a solution which doesn't increase the API surface of the library though.

I'm quite convinced you can obtain the same result by implementing your own DateRangeLimiter.

i'm going to close the PR, not because I don't like the contribution (I really do), but because I'm very cautious about increasing the things I have to support.

**Pull request closed without merging**
