### PR TITLE
Support for v4

### PR DESCRIPTION
**Pull request by bita147**

### CODE REVIEW

**Comment by wdullaer** [comment]
There are two issues with this pull request:
1. You only modified the date picker, you should modify the timepicker as well
2. I don't intend to support versions before Android 4.0. They account for about 7% of the entire market and are on decline. If you set your minimum level sufficiently high, the activity object will support `getFragmentManager()` regardless of whether you use AppCompat or not.
This is less intrusive than the other way around: people not using AppCompat do not have `getSupportFragmentManager()` on their Activity and will not be able to use the library.

**Comment by MaciejCzekanski** [comment]
2. If you want use Toolbar API before 5.0, you have to use ActionBarActivity (from appcompat lib) and v4 Fragments. I hate that, but I don't see any way around. Therefore, I think your dialogs should work with and without support lib.

**Comment by wdullaer** [comment]
I'm using the normal `FragmentManager` just fine in an `ActionBarActivity` in one of my apps.
This library is working just fine in that app as well.

Provided the minAPI of your project is high enough, it will support `getFragmentManager()`
I do not intend to support pre-ICS versions of android. It's a negligible part of the market.

**Comment by MaciejCzekanski** [comment]
Yeah, this is how I fixed the problem. I tried to use get(Support)FragmentManager in v4 Fragment, but types were incompatible. getActivity().getFragmentManager() did the trick though.

I just wonder if it is safe to mix usage of both native and support FragmentManagers.

**Comment by wdullaer** [comment]
I need to check, but I don't think I use `getSupportFragmentManager()` at all. I set the `Toolbar` in the `ActionBarActivity` and then just call `getActionBar()` in regular `Fragment`s.

If I remember correctly the support library implementation falls back to the native implementation if it is present on the system, so I think you're safe.

**Comment by MaciejCzekanski** [comment]
According to the manual (http://developer.android.com/reference/android/support/v4/app/Fragment.html), v4 Fragment is used even above Android 3.0. But so far it seems to work just fine :)

**Pull request closed without merging**
