### PR TITLE
Simple implementation of setMinTime and setMaxTime

### PR DESCRIPTION
**Pull request by emilianobonassi**
It will solve #61 and #86 .
Todo:
- improve quality of code
- instrumentation tests

### CODE REVIEW

**Comment by wdullaer** [comment]
Thanks.

I'll have a look at this shortly

**Comment by emilianobonassi** [comment]
You're welcome.

**Comment by emilianobonassi** [comment]
@wdullaer , did you have time to look the changes?

**Comment by wdullaer** [comment]
Not yet. I haven't had enough time yet to look at the bigger chunks of work for this project.
I hope to get around to it somewhere this week/weekend.

**Comment by emilianobonassi** [comment]
:+1: , I thought you had issues with my changes.

**Comment by wdullaer** [comment]
Just some update on this.
I have been busy implementing this feature based on your pull request.
Because I had refactored some of the library before you did the pull request, and because I needed to foresee compatibility with #104 I thought it was better not to merge and resolve conflicts, but to use your PR as inspiration.

I'm now crushing the last bugs on this, so expect it in master somewhere this week.

**Comment by emilianobonassi** [comment]
Thanks @wdullaer for your update, you are very kind.
Anyway, it's a PR not an order to merge :smile: , I'm glad that you are using this as inspiration.
Let me know if you need help to reduce your load.

**Comment by wdullaer** [comment]
Thanks for the offer.
I'm thinking about setting up a gitter channel.
This should make support easier, keeping questions out of the bug tracker, but it should also make it easier for people to help me out with coding. Closer feedback loop.

**Pull request closed without merging**
