### PR TITLE
Replace ListView with RecyclerView

### PR DESCRIPTION
**Pull request by carlonzo**
I have replaced the ListView of the DayPickerView with a RecyclerView and applied few optimisation to the adapter. 

I need to reformat the code. where can I find the formatter?

### CODE REVIEW

**Comment by wdullaer** [comment]
This was on my list of things to do.
I'll definitely be taking a closer look at this.

I'm not sure I understand what you mean with a formatter. Are you looking for a gradle task that applies a code style?

**Comment by carlonzo** [comment]
I'm glad you will consider it. 
as you can see the codestyles in my AndroidStudio have changed everything.

**Comment by wdullaer** [comment]
You're right: having a code style will make contributing easier.
Let me see if I can make one that more or less matches the current style (it's a bit of a mess already)

**Comment by carlonzo** [comment]
sounds great!
also I have other big changes I have done on this code, (like I have extracted the controller from the Dialog, so the DayPickerView is now independent, or I have profiled and optimised some parts), and I would like to discuss with you if you are interested in receiving PRs like that

**Comment by wdullaer** [comment]
Definitely. Seems like you have the time I lack at the moment.
Let me block some time to go through your existing PRs at a high level, and then we can set something up.

**Comment by wdullaer** [comment]
I read through the code and this looks good to me.
I need to find some time to test the result on my test devices, but after that this should be good to go.

It will also make implementing horizontal scrolling in the version 2 layout a lot easier 👍

**Comment by carlonzo** [comment]
I was about to send you a message. this code is not ready yet (the scrolling is not very natural). On a separate implementation I have replaced the RecyclerView with this PagerView implementation using a RecyclerView (https://github.com/lsjwzh/RecyclerViewPager/blob/master/lib/src/main/java/com/lsjwzh/widget/recyclerviewpager/RecyclerViewPager.java) an it looks much more natural and smooth. I may consider to copy the logic for the scrolling and add it here

**Comment by wdullaer** [comment]
I'm really interested in this PR, so please update it.
Let me know when I should take a look at it again

**Comment by carlonzo** [comment]
I totally forgot to fix my PR. I have also realised that in support library 24.2.0 they have released a SnapHelper (https://rubensousa.github.io/2016/08/recyclerviewsnap) which can be helpful here. I need to find some time to fix it. sorry!

**Comment by wdullaer** [comment]
Good stuff. I'm really looking forward to this one.

**Pull request merged**
