### PR TITLE
Functionality allowing individual days in calendar to be highlighted

### PR DESCRIPTION
**Pull request by enyciaa**
An array of days to be highlighted (in the form of a multi-dimensional array containing day/month/year for each date to be highlighted) can be passed to the DatePickerDialog - 

The highlighted / non-highlighted day text colors can be edited by defining colors in your main colors.xml file:
Highlighted text color res -  mdtp_date_picker_text_normal
Non-highlighted text color res - mdtp_date_picker_text_not_highlighted

### CODE REVIEW

**Comment by wdullaer** [comment]
It might take a few days until I can check this in detail.

Do you have a screenshot of what the end result would look like?

**Comment by enyciaa** [comment]
screenshot_2015-06-16-09-05-03

**Comment by wdullaer** [comment]
You're using the disabled color for the not highlighted days.
Is the goal of the highlight that these are the only possible selections, or to indicate that something else is already happening on these days?

I was thinking of refactoring this in two methods:

**1. setSelectableDates()**
This would visualise like your example, but make the grey dates non selectable

**2. setHighlightedDates()**
This would make the highlighted dates bold, and keep the normal dates "normal". Any date would be selectable

Any thoughts?

**Comment by enyciaa** [comment]
My goal was to highlight the days that contained saved data. So highlighted days took the standard text color (mdtp_date_picker_text_normal) and non-highlighted days took a new color I added in color.xml (mdtp_date_picker_text_not_highlighted - which uses #ccc, the same as disabled text) - Both colors can be overridden but it's perhaps a little counter-intuitive.

The original code has an implementation for setting selectable dates in isOutOfRange(), which disables all the days outside the min and max dates (which can be set in DatePickerDialog.java) - but doesn't allow disabling individual dates. 

My thoughts are that creating a setSelectableDates() function to make individual dates un-selectable could prove problamatic, as you'd also need to make it so the days can't be selected when touched, which would require more changes. Depends if you can see an easy way to achieve that?

Let me know if you have any other questions

**Comment by wdullaer** [comment]
I quite like the patch, but the way you've set the default colors suggests that the days are not selectable, while they are.

I probably have to go into the touch code anyway, because setMaxDate and setMinDate stop working after an orientation change.

I also don't like the fact that you've changed the signature of DatePickerDialog.newInstanc(). This breaks the API (easy to fix with an overloaded version).

I'll probably tweak your code a bit before merging.

**Comment by wdullaer** [comment]
I heavily refactored your code.
There is now a setSelectableDays and setHighlightedDays.
Both take an array of Calendar objects.

Highlighted days will render in bold. If you want to have it render like your example, you can overwrite `mdtp_date_picker_text_normal` and `mdtp_date_picker_text_highlighted`

I will release a new version to Maven Central later this week.

**Comment by enyciaa** [comment]
Great! I look forward to using it!

Should I close the pull request now?

**Pull request merged**
